%{

This is a partial/scratch script that I created for collating the quick
envelope statistics generated by Power (Hilbert) across participants. The
statistical collation/analysis code added to Envelope Viewer is much more
full-featured so I EOL'ed this approach, but some may still find it useful
to build from. Not ready for turnkey use, but here as reference.

- ABF 2022-05-30

%}

function PSGpower_penvcollate()

%Get list of data to process
[~,penvfp] = uigetfile('*_envelq_*.mat', 'Select a *_envelq_*.mat file from the folder containing all *_envelq_*.mats you want to process');
cd(penvfp);
pefns = dir([penvfp '*_envelq_*.mat']);
pefns = {pefns.name};
outmat = cell(length(pefns), 1 + 31, 4);
headers{1} = {'PID', 'pidid', 'date', 'band', 'dv'};

for p = 1:length(pefns)
    pidparts = strsplit(pefns{p}, '_');
    pidid = pidparts{1};
    piddate = pidparts{~cellfun(@isempty, regexp(pidparts, '\d\d\d\d\d\d'))};
    pidband = strrep(pidparts{~cellfun(@isempty, regexp(pidparts, 'subdelta|delta|theta|sigma'))}, '.mat', '');
    pid = [pidid '_' piddate '_' pidband];
    
    disp(['Processing ' pid ', data file ' num2str(p) ' of ' num2str(length(pefns)) '...']);
    
    % Import the file
    envelq = load('-mat', [penvfp pefns{p}]);
    envelq = envelq.envelq;
    
    for dv = 3:numel(fieldnames(envelq)) %DVs, starts at 3 to skip PID and channel name columns
        curheader = headers{1};
        dvname = fieldnames(envelq)';
        dvname = dvname{dv};
        for ch = 1:length(envelq) %channels
            chid  = envelq(ch).chan;
            while all(cellfun(@isempty, regexp(curheader, chid)))
                curheader = [curheader chid];
            end
            curcol = find(~cellfun(@isempty, regexp(curheader, chid)));
            outmat{p,1,dv} = pid;
            outmat{p,2,dv} = pidid;
            outmat{p,3,dv} = piddate;
            outmat{p,4,dv} = pidband;
            outmat{p,5,dv} = dvname;
            outmat{p,curcol,dv} = envelq(ch).(dvname);
        end %Channel loop
        headers{dv} = curheader;
    end %DV loop
end %Participant loop

%Write out .csvs with data
[~, outfp] = uiputfile([penvfp 'temp.csv'], 'Where to save collated .csv files?');
for dv = 3:size(outmat,3)
    outfn = ['penvcollate_' outmat{1,find(strcmp(headers{1},'band')),dv} '_' outmat{1,find(strcmp(headers{1},'dv')),dv} '_' datestr(now, 'mm-dd-yyyy') '.csv'];
    outfid = fopen([outfp outfn], 'w+');
    fprintf(outfid, [repmat('%s,',1,size(outmat,2)-1) '%s\n'], headers{dv}{:});
    for r = 1:size(outmat,1)
        fprintf(outfid, [repmat('%s,',1,length(headers{1})) repmat('%f,',1,size(outmat,2) - length(headers{1}) - 1) '%f\n'], outmat{r,:,dv});
    end
    fclose(outfid);
end

end %Function